psalm.xml
Hello,
This simple change adds a `psalm.xml` configuration file for [Psalm](https://github.com/vimeo/psalm) static analyzer.
Add the `psalm.phar` (from the [releases page](https://github.com/vimeo/psalm/releases)) in your `$PATH` and just do `psalm` to get something like:
As you can see, a bunch of errors are found. Some that might be quite hard to spot without a tool like this one.
Best,
~Nico
=> Add psalm.xml config file

composer.json
`tightenco/collect` <5.6 has an older namespace which is incompatible with version 5.6 onwards. This should have no minimum requirement issues as 5.6 requires PHP 7.1 and this package is PHP 7.2 minimum.
I only [noticed this](https://github.com/iter8-au/ldaprecord-bundle/runs/2129510303?check_suite_focus=true) when setting up GitHub Actions for my [Symfony Bundle](https://github.com/iter8-au/ldaprecord-bundle) of this great package.
=> Bump minimum `tightenco/collect` library to ^5.6

src/Query/Model/ActiveDirectoryBuilder.php
I'm glad you fixed a lot of the psalm reported issues ;) Static analysis in php is very useful.
This is just a small typo fix to bring it down from 1 to 0!
Still 401 other issues, but at least no errors now!
Now that you don't have any errors anymore you can add it to the tests!
=> Fix typo in docblock and remove a few whitespaces

src/Models/ActiveDirectory/Entry.php, src/Models/Concerns/HasAttributes.php, src/Models/Model.php, tests/Models/ModelTest.php
Related #354 
- When models have their `dn` or `distinguishedname` attribute set, the models `$dn` property is now properly updated to its value
- `Model::make()` method for making new model instances fluently without saving them
- `$model->setRawAttribute($key, $value)` has been added to allow direct access to the `$attributes` property without triggering mutators
=> Fix applying distinguished name to Model's when `fill()`'ed or set via attribute

.gitignore, src/Events/Logger.php, src/Events/NullDispatcher.php, src/HandlesConnection.php, src/Ldap.php, src/LdapInterface.php, src/Models/Attributes/AccountControl.php, src/Models/Attributes/DistinguishedName.php, src/Models/Attributes/DistinguishedNameBuilder.php, src/Models/Attributes/Timestamp.php, src/Models/Concerns/CanAuthenticate.php, src/Models/Model.php, src/Models/Relations/OneToMany.php, src/Query/Collection.php, src/Query/Events/QueryExecuted.php, src/Query/ObjectNotFoundException.php, src/Query/Pagination/AbstractPaginator.php, src/Query/Pagination/Paginator.php
I tried to change the Psalm level to 6 to see what kind of error was reported.
I've fixed some of them.
The remaining errors are mostly related to the builder class and will require more effort to be fixed.
There is also one false positive but I have open a PR to fix it: https://github.com/vimeo/psalm/pull/7145
=> Fix some type issues

src/Query/Pagination/AbstractPaginator.php
Since `$cookie` is always a string we can simplify the way to check if it's empty.
=> Simplify shouldContinue()

src/Query/Builder.php, src/Query/Pagination/Paginator.php, tests/Models/ModelScopeTest.php, tests/Query/BuilderTest.php
This PR introduces the ability to sort LDAP results server-side, instead of relying on client side sorting, which can be resource intensive with large sets of results. It also works with paginated requests (which means it also works via chunking).
This PR also introduces a new public property `$controlsResponse` on the query builder which will be populated after a query is executed, allowing us to look at the controls sent back from the server and identify any potential issues.
=> Feature - Server Side Sorting

src/Query/Builder.php
This fixes a bug that got introduced in the last commit which always returns 0 as the total count.
=> Use correct key to retrieve total count of results

src/Models/ActiveDirectory/Entry.php, src/Models/Concerns/HasAttributes.php, src/Models/Concerns/SerializesAndRestoresPropertyValues.php, src/Models/Model.php, tests/Unit/Models/ModelSerializationTest.php
Closes #457
This PR implements un-serialization logic to convert transformed values back into their true LDAP counterparts.
=> Fix model un-serialization

src/Models/Collection.php, src/Models/Relations/HasMany.php, src/Query/Builder.php, tests/Unit/Models/ModelHasManyTest.php
Closes https://github.com/DirectoryTree/LdapRecord/issues/409
This PR also adds:
- `Models\Collection::modelDns()` method to easily fetch all of the model's Distinguished Name's inside of a model collection. This is a parity feature of the Eloquent Collection `modelKeys()` method.
- `HasMany::each($callback)` method to iterate through each result of a chunked query via callback.
=> Add ability to chunk relations recursively

src/Models/Relations/Relation.php
Closes #443
@yakatz will this work for you?
```php
use LdapRecord\Models\Relations\Relation;
Relation::setModelResolver(function ($modelObjectClasses, $relationMap, Model $model) {
// Determine and return model class using custom matching algo...
});
```
=> Add ability to override model matching using relation static callback

src/Models/Concerns/CanAuthenticate.php, src/Models/Concerns/HasEvents.php, src/Models/Concerns/HasGlobalScopes.php, src/Models/Concerns/HasPassword.php, src/Models/Concerns/HasScopes.php, src/Models/Concerns/HidesAttributes.php, tests/Unit/Models/ActiveDirectory/UserTest.php
=> Properly set the LDAP batch modification type of password when user does not exist

src/Models/Relations/Relation.php, tests/Unit/Models/ModelHasManyTest.php
Related https://github.com/DirectoryTree/LdapRecord/issues/484
This PR implements the ability for devs to apply a subsequent method call to relations when querying or defining them to reject any models that are returned from the query that do not have the object classes specified in their `$objectClasses` property:
**Applying Dynamically**:
```php
$group = Group::find('cn=accounting,dc=local,dc=com');
$group->members()->onlyRelated()->get();
```
**Applying in Relation Definition**:
```php
class Group extends Model
{
public function members()
{
return $this->hasMany([User::class, Group::class])->onlyRelated();
}
}
```
=> Add ability to filter relations based on related object classes

src/Models/Attributes/Password.php, tests/Unit/Models/Attributes/PasswordTest.php
Altough largely deprecated, NTHASH / NTLM is sometimes mandatory (RADIUS authentication)
=> Add Password::nthash implementation

src/Connection.php, src/Models/Model.php, src/Query/Builder.php, tests/Integration/ConnectionTest.php, tests/Unit/ConnectionTest.php, tests/Unit/Models/ModelQueryTest.php
Closes #541 
This PR implements dynamically creating new connections when chunking a query.
This allows simultaneous pagination queries that contain cookies to be executed on servers that do not actually support it.
=> Run chunking in isolated connections

src/Models/Attributes/Timestamp.php, tests/Unit/Models/ActiveDirectory/UserTest.php, tests/Unit/Models/Attributes/TimestampTest.php
Closes #552
This PR implements appropriate handling of Windows Integer time maximum or minimum values (`0` and `9223372036854775807`).
If a `windows-int` based cast is used on a model and the value is equal to either of the above mentioned values, then those values will be returned, instead of a `Carbon` instance.
=> Appropriately handle maximum and minimum values of windows integer time

src/Query/Builder.php, src/Testing/LdapFake.php, tests/Integration/CacheTest.php, tests/Unit/Query/BuilderCacheTest.php
The LDAP host is part of the cache key, but the host is only set after the first connection. This patch ensures that host is always set before the finding the cache key.
Without this patch you'll get wrong results if your site/script as the first thing tries to do the same query on multiple connections. Further, you are not caching results as expected. Consider the following "script": 
1. `Entry::on('a')->cache(...)->where('k1','=','1')->get();` # new connection, saves result with host=`null`
2. `Entry::on('b')->cache(...)->where('k1','=','1')->get();` # you get the (wrong) results from connection a
3. `Entry::on('c')->cache(...)->where('k1,'=','1')->get();` # you get the (wrong) results from connection a
4. `Entry::on('a')->cache(...)->where('k1','=','1')->get();` # not using cache from …
=> Ensure that host is set, before finding cache key

src/Models/Collection.php, tests/Unit/Models/ModelRelationTest.php
I noticed while I was making an authentication rule, that the validation would fail, even though I was sure that the DN was correctly given.
Turns out that providing a string wouldn't work while providing the same string within `Group::findOrFail` would work if the DN provided by the LDAP server has a different case, like `cn=foo,dc=local,dc=com`.
Works:
```php
return $this->user->groups()->exists(
Group::findOrFail('CN=foo,DC=local,DC=com')
);
```
Doesn't work:
```php
return $this->user->groups()->exists(
'CN=foo,DC=local,DC=com'
);
```
=> Case insensitive DN comparison

src/Models/Collection.php, tests/Unit/Models/ModelRelationTest.php
Ported from #607 
---
> I noticed while I was making an authentication rule, that the validation would fail, even though I was sure that the DN was correctly given.
> 
> Turns out that providing a string wouldn't work while providing the same string within `Group::findOrFail` would work if the DN provided by the LDAP server has a different case, like `cn=foo,dc=local,dc=com`.
> 
> Works:
> ```php
> return $this->user->groups()->exists(
>     Group::findOrFail('CN=foo,DC=local,DC=com')
> );
> ```
> 
> Doesn't work:
> ```php
> return $this->user->groups()->exists(
>     'CN=foo,DC=local,DC=com'
> );
> ```
=> [2.x] Case insensitive DN comparison

src/Models/Model.php
This commit fixes the way RDN is compared when renaming an object, in that if the RDN attribute is ommited it will be appended to the string before comparing it with the Models RDN.
e.g. if supplied with an OU named 'TestOU' and we called `$TestOU->rename('TestOU');` by the time the comparison is run this is the value of `$rdn` and `$this->getRdn()` being compared:
By placing the RDN fixer code above the RDN check code this solves the issue of a non-complete RDN causing an unnessicary update on the LDAP server.
=> Fix RDN comparison in model rename function

src/Models/Attributes/AccountControl.php, src/Models/Attributes/DistinguishedName.php, src/Models/Attributes/DistinguishedNameBuilder.php, src/Models/Attributes/EscapedValue.php, src/Models/Attributes/Guid.php, src/Models/Attributes/Sid.php, src/Models/Model.php
Since this project now requires a minimum PHP version of 8.1, PHP 8.0 introduced a new interface called [Stringable](https://www.php.net/manual/en/class.stringable.php) which we are able to explicitly implement.
As the excerpt from the linked docs states above, although any class implementing `__toString()` will automatically gain the Stringable interface, it can and **should** be declared explicitly (presumably for future versions of PHP, and IDE help etc).
This PR implements Stringable to all classes implementing the `__toString()` method.
=> Adds Stringable interface to all classes containing __toString() method.

src/Models/Relations/Relation.php, tests/Unit/Models/ModelRelationTest.php
=> Bug 634 - Relation::setModelResolver in AppServiceProvider no longer works in v3

src/Models/Concerns/HasAttributes.php, src/Models/Model.php, tests/Unit/Models/ModelTest.php
This PR implements the ability to retrieve changes on a model after an update has been performed.
This is really handy to be able to retrieve all of the changed attributes of a model, _after_ an update:
```php
use LdapRecord\Models\Entry;
$model = Entry::find('cn=jdoe,dc=local,dc=com');
$model->mail = 'foo@email.com';
$model->save();
$model->wasChanged(); // true
$model->wasChanged('mail'); // true
$model->wasChanged('invalid'); // false
$model->wasChanged(['mail', 'invalid']); // true
$model->getChanges(); // ['mail' => ['foo@email.com']]
```
=> Add "changes" API to models

src/Models/Concerns/HasAttributes.php
As described here - https://www.php.net/manual/en/function.utf8-encode.php - utf8_encode is deprecated in PHP 8.2
=> Replace deprecated utf8_encode

src/Models/ActiveDirectory/User.php, src/Models/Concerns/CanAuthenticate.php, src/Models/OpenLDAP/User.php, tests/Unit/Models/ActiveDirectory/UserTest.php, tests/Unit/Models/OpenLDAP/UserTest.php
=> Bug 688 - `getAuthIdentifier` for OpenLDAP users returns incorrect value

src/Query/Builder.php, tests/Unit/Query/BuilderTest.php
=> Bug 687 - `orWhere` cannot be called without an operator

src/Auth/Events/Failed.php, src/Auth/Guard.php, tests/Unit/Auth/GuardTest.php, tests/Unit/Log/EventLoggerTest.php
Related https://github.com/DirectoryTree/LdapRecord/discussions/708
This PR adds the `BindException` to the `Failed` event to provide additional debugging functionality to developers listening to the event.
=> Add `BindException` to `Failed` event for additional debugging information

src/Models/Concerns/HasAttributes.php, tests/Unit/Models/ModelAttributeCastTest.php
Closes #707 
This PR implements reverse casting that previously did not exist, as discovered by @lukasmu.
This means that attributes on LDAP models can now be set to primitives, such as booleans:
```php
$user = User::findOrFail('...');
$user->msExchHideFromAddressList = true;
// ['TRUE']
var_dump($user->getRawAttribute('msExchHideFromAddressList'));
```
And objects, such as dates:
```php
$user = User::findOrFail('...');
$user->accountExpires = new \DateTime('2020-10-02 02:22:09');
// ['132460789290000000']
var_dump($user->getRawAttribute('accountExpires'));
```
=> Bug 707 - Attribute casting seem to work only in one direction

src/Models/Concerns/HasAttributes.php, tests/Unit/Models/ModelAttributeCastTest.php
=> Bug 714 - Reverse boolean casts no longer accept LDAP string booleans

src/Testing/DirectoryFake.php, tests/Unit/Testing/DirectoryFakeTest.php
Closes https://github.com/DirectoryTree/LdapRecord-Laravel/issues/653
=> Flush container on DirectoryFake::tearDown

src/Models/Collection.php, src/Models/Model.php, tests/Unit/Models/CollectionTest.php, tests/Unit/Models/ModelSerializationTest.php
=> Bug 746 - Infinite loop in LdapRecord\Models\Collection::contains function

src/Query/Builder.php, tests/Unit/Query/BuilderTest.php
=> Feature 744 - Add ability to provide LDAP control options to orderBy

src/Models/Model.php, tests/Unit/Models/ModelTest.php
=> Bug 753 - Ensure model attribute values are numerically indexed upon creation

src/Query/Builder.php, tests/Integration/QueryTest.php
=> Bug 761 - Properly override query limit to `0` when chunking

src/Query/Model/ActiveDirectoryBuilder.php, tests/Unit/Query/Model/ActiveDirectoryTest.php
=> Bug 766 - {base} inside whereMemberOf doesn't work
