src/Models/Attributes/AccountControl.php

https://github.com/DirectoryTree/LdapRecord/issues/90

Add PASSWD_CANT_CHANGE const

---

src/Models/Relations/Relation.php

Rename $classes to $objectClasses

---

src/Models/Model.php
tests/Models/ModelTest.php

If the original attribute is not updated as well a change would be
detected on save.

Update original name attribute on rename

---

src/Models/Freeipa/Entry.php
src/Models/Freeipa/Group.php
src/Models/Freeipa/Scopes/AddEntryUuidToSelects.php
src/Models/Freeipa/User.php
src/Query/Model/FreeIpaBuilder.php

Hi
This is working fine with our FreeIPA server 4.6.5
Let me know if the code is not syntaxed correct or if something is wrong

Added FreeIpa support

---

src/Models/FreeIPA/Group.php
src/Models/FreeIPA/User.php

Having the auxiliary classes could lead to some search/find problems

Removed auxiliary classes from $objectClasses

---

src/Models/ActiveDirectory/Group.php
src/Models/ActiveDirectory/User.php
src/Models/OpenLDAP/User.php
src/Models/Relations/Relation.php
tests/Models/ActiveDirectory/GroupTest.php
tests/Models/ModelHasOneTest.php

Closes https://github.com/DirectoryTree/LdapRecord-Laravel/issues/217

Added OpenLDAP User groups relationship

---

src/Query/Pagination/Paginator.php

Use null coalescent operator

---

src/Ldap.php
src/Query/Builder.php

Patch php 8.1 support

---

src/LdapInterface.php
src/Models/ActiveDirectory/User.php
src/Models/Attributes/AccountControl.php
src/Models/Attributes/Password.php
src/Models/Attributes/TSProperty.php
src/Models/Attributes/TSPropertyArray.php
src/Models/BatchModification.php
tests/Unit/Models/ActiveDirectory/UserTest.php

Add ability to easily retrieve `AccountControl` object from the `User` Active Directory model

---

src/Models/Concerns/HasEvents.php
src/Models/Model.php

Bug 508 - Events not firing when updating group

---

src/Models/Concerns/HasPassword.php
tests/Unit/Models/ActiveDirectory/UserTest.php

Closes #514
Closes #554 
Related #506

Revert #506

---

src/Query/Model/Builder.php

Fix return types on model builder

---

composer.json
src/Query/ArrayCacheStore.php

Closes https://github.com/DirectoryTree/LdapRecord-Laravel/issues/541

Bug 541 - PSR-SimpleCache >= v2.0 not available in Laravel 8

---

src/Models/Concerns/HasPassword.php
tests/Unit/Models/ActiveDirectory/UserTest.php

Bug 616 - Strange behavior unicodepwd and userAccountControl

---

src/Models/ActiveDirectory/Computer.php

Add `AccountControl` trait to computer model

---

src/Query/Filter/ConditionNode.php
tests/Unit/Query/Filter/ParserTest.php

Closes https://github.com/DirectoryTree/LdapRecord/issues/652

Fix invalid query filter when using memberof

---

src/Query/Builder.php
src/Query/Model/Builder.php
tests/Unit/Models/ActiveDirectory/ModelTest.php

Bug 655 - Groups relation Builder TypeError

---

src/Query/Builder.php
src/Query/Model/Builder.php

Bug 676 -  Missing return type findManyBy()

---

src/Connection.php
src/Models/Model.php
src/Models/Relations/Relation.php
src/Query/ObjectNotFoundException.php
tests/Unit/Models/ModelHasManyTest.php
tests/Unit/Models/ModelTest.php

Feature 640 - Add ability to morph models into other models based on object classes

---

src/Configuration/DomainConfiguration.php
src/Models/Attributes/TSProperty.php
src/Models/Concerns/HasPassword.php
tests/Unit/Configuration/DomainConfigurationTest.php
tests/Unit/FakeDirectoryTest.php

Feature 700 - [Feature] Disable mandatory TLS connection for localhost

---

src/Auth/Guard.php
src/HandlesConnection.php
src/Ldap.php
src/LdapInterface.php
src/Testing/LdapFake.php
tests/Unit/Auth/GuardTest.php
tests/Unit/LdapTest.php

Bug 669 - [Bug] ldap_start_tls(): Unable to start TLS: Local error

---

src/Models/Attributes/Timestamp.php
tests/Unit/Models/Attributes/TimestampTest.php
tests/Unit/Models/ModelAccessorMutatorTest.php
tests/Unit/Models/ModelAttributeCastTest.php
tests/Unit/Models/ModelSerializationTest.php
tests/Unit/Testing/AuthGuardFakeTest.php
tests/Unit/Testing/ConnectionFakeTest.php
tests/Unit/Testing/DirectoryFakeTest.php

Feature 745 - [Feature] Support for LDAP milliseconds format
